controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    hqp_controller:
      type: hqp_controller/HQPController #forward_command_controller/ForwardCommandController
      
    # effort_controllers:
    #   type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

hqp_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
      - panda_finger_joint1
      - panda_finger_joint2
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      # - effort
    interface_name:
      effort
effort_controllers:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort